//Package po generated by 'freedom new-po'
package po

import ()

// Dump .
type Dump struct {
	changes map[string]interface{}
	ID      int    `gorm:"primary_key;column:id"`
	Name    string `gorm:"column:name"` // 管理员名称
	Dump    string `gorm:"column:dump"`
}

// TableName .
func (obj *Dump) TableName() string {
	return "dump"
}

// TakeChanges .
func (obj *Dump) TakeChanges() map[string]interface{} {
	if obj.changes == nil {
		return nil
	}
	result := make(map[string]interface{})
	for k, v := range obj.changes {
		result[k] = v
	}
	obj.changes = nil
	return result
}

// updateChanges .
func (obj *Dump) setChanges(name string, value interface{}) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.changes[name] = value
}

// SetName .
func (obj *Dump) SetName(name string) {
	obj.Name = name
	obj.setChanges("name", name)
}

// SetDump .
func (obj *Dump) SetDump(dump string) {
	obj.Dump = dump
	obj.setChanges("dump", dump)
}
